//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copreter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Copreter.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string BTN_Aceptar {
            get {
                return ResourceManager.GetString("BTN_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string BTN_Actualizar {
            get {
                return ResourceManager.GetString("BTN_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BTN_Cancelar {
            get {
                return ResourceManager.GetString("BTN_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string BTN_Crear {
            get {
                return ResourceManager.GetString("BTN_Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string BTN_Editar {
            get {
                return ResourceManager.GetString("BTN_Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string BTN_Filtrar {
            get {
                return ResourceManager.GetString("BTN_Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string BTN_Guardar {
            get {
                return ResourceManager.GetString("BTN_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        public static string BTN_Pagar {
            get {
                return ResourceManager.GetString("BTN_Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string BTN_Volver {
            get {
                return ResourceManager.GetString("BTN_Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string CARD_TITLE {
            get {
                return ResourceManager.GetString("CARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string CITA_Estado {
            get {
                return ResourceManager.GetString("CITA_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string CITA_Fecha {
            get {
                return ResourceManager.GetString("CITA_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string CITA_Hora {
            get {
                return ResourceManager.GetString("CITA_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lugar.
        /// </summary>
        public static string CITA_Lugar {
            get {
                return ResourceManager.GetString("CITA_Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la Empresa.
        /// </summary>
        public static string CITA_Nombre_Empresa {
            get {
                return ResourceManager.GetString("CITA_Nombre_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la Obra.
        /// </summary>
        public static string CITA_Nombre_Obra {
            get {
                return ResourceManager.GetString("CITA_Nombre_Obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Cita.
        /// </summary>
        public static string CITA_Nro {
            get {
                return ResourceManager.GetString("CITA_Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra.
        /// </summary>
        public static string CITA_Obra {
            get {
                return ResourceManager.GetString("CITA_Obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cita.
        /// </summary>
        public static string CITA_Titulo {
            get {
                return ResourceManager.GetString("CITA_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizar.
        /// </summary>
        public static string COTIZACION_COTIZAR {
            get {
                return ResourceManager.GetString("COTIZACION_COTIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizar.
        /// </summary>
        public static string COTIZACION_COTIZAR_Titulo {
            get {
                return ResourceManager.GetString("COTIZACION_COTIZAR_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string COTIZACION_Estado {
            get {
                return ResourceManager.GetString("COTIZACION_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string COTIZACION_Fecha {
            get {
                return ResourceManager.GetString("COTIZACION_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Cotización.
        /// </summary>
        public static string COTIZACION_Nro {
            get {
                return ResourceManager.GetString("COTIZACION_Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Obra.
        /// </summary>
        public static string COTIZACION_Obra {
            get {
                return ResourceManager.GetString("COTIZACION_Obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotización.
        /// </summary>
        public static string COTIZACION_Titulo {
            get {
                return ResourceManager.GetString("COTIZACION_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string COTIZACION_Total {
            get {
                return ResourceManager.GetString("COTIZACION_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1º Pago.
        /// </summary>
        public static string FACTURA_1Pago {
            get {
                return ResourceManager.GetString("FACTURA_1Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2º Pago.
        /// </summary>
        public static string FACTURA_2Pago {
            get {
                return ResourceManager.GetString("FACTURA_2Pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar Factura.
        /// </summary>
        public static string FACTURA_Descargar {
            get {
                return ResourceManager.GetString("FACTURA_Descargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Factura.
        /// </summary>
        public static string FACTURA_Enviar {
            get {
                return ResourceManager.GetString("FACTURA_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Factura.
        /// </summary>
        public static string FACTURA_Factura {
            get {
                return ResourceManager.GetString("FACTURA_Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string FACTURA_Fecha {
            get {
                return ResourceManager.GetString("FACTURA_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Cotización.
        /// </summary>
        public static string FACTURA_NroCotizacion {
            get {
                return ResourceManager.GetString("FACTURA_NroCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura.
        /// </summary>
        public static string FACTURA_Titulo {
            get {
                return ResourceManager.GetString("FACTURA_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string FACTURA_Total {
            get {
                return ResourceManager.GetString("FACTURA_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string INCIDENCIA_Descripcion {
            get {
                return ResourceManager.GetString("INCIDENCIA_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string INCIDENCIA_Fecha {
            get {
                return ResourceManager.GetString("INCIDENCIA_Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horas Trabajadas.
        /// </summary>
        public static string INCIDENCIA_Hora {
            get {
                return ResourceManager.GetString("INCIDENCIA_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string INCIDENCIA_Pedido {
            get {
                return ResourceManager.GetString("INCIDENCIA_Pedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incidencia.
        /// </summary>
        public static string INCIDENCIA_Titulo {
            get {
                return ResourceManager.GetString("INCIDENCIA_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar Clientes.
        /// </summary>
        public static string MANU_CLIENTE_TODOS {
            get {
                return ResourceManager.GetString("MANU_CLIENTE_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de eliminar el registro.
        /// </summary>
        public static string MENSAJE_CONFIRMAR_ELIMINAR {
            get {
                return ResourceManager.GetString("MENSAJE_CONFIRMAR_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Usuarios.
        /// </summary>
        public static string MENU_ACCESO_TODOS {
            get {
                return ResourceManager.GetString("MENU_ACCESO_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptado.
        /// </summary>
        public static string MENU_ACEPTADOS {
            get {
                return ResourceManager.GetString("MENU_ACEPTADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alquiler.
        /// </summary>
        public static string MENU_ALQUILER {
            get {
                return ResourceManager.GetString("MENU_ALQUILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citas.
        /// </summary>
        public static string MENU_CITA {
            get {
                return ResourceManager.GetString("MENU_CITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En espera.
        /// </summary>
        public static string MENU_COTIZACION_ESPERA {
            get {
                return ResourceManager.GetString("MENU_COTIZACION_ESPERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotizaciones.
        /// </summary>
        public static string MENU_COTIZACION_TODOS {
            get {
                return ResourceManager.GetString("MENU_COTIZACION_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Alquiler.
        /// </summary>
        public static string MENU_GESTIONAR_ALQUILER {
            get {
                return ResourceManager.GetString("MENU_GESTIONAR_ALQUILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Cotizacón.
        /// </summary>
        public static string MENU_OBRA_NUEVO {
            get {
                return ResourceManager.GetString("MENU_OBRA_NUEVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Cotizaciones.
        /// </summary>
        public static string MENU_OBRA_TODOS {
            get {
                return ResourceManager.GetString("MENU_OBRA_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Partida.
        /// </summary>
        public static string MENU_PARTIDA_GESTIONAR {
            get {
                return ResourceManager.GetString("MENU_PARTIDA_GESTIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas.
        /// </summary>
        public static string MENU_PARTIDA_TODOS {
            get {
                return ResourceManager.GetString("MENU_PARTIDA_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por asignar.
        /// </summary>
        public static string MENU_PEDIDO_POR_ASIGNAR {
            get {
                return ResourceManager.GetString("MENU_PEDIDO_POR_ASIGNAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedidos.
        /// </summary>
        public static string MENU_PEDIDO_TODOS {
            get {
                return ResourceManager.GetString("MENU_PEDIDO_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        public static string MENU_PENDIENTE {
            get {
                return ResourceManager.GetString("MENU_PENDIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string MENU_SALIR {
            get {
                return ResourceManager.GetString("MENU_SALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Partida.
        /// </summary>
        public static string MENU_TIPO_PARTIDA {
            get {
                return ResourceManager.GetString("MENU_TIPO_PARTIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string MENU_TODOS {
            get {
                return ResourceManager.GetString("MENU_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Trabajadores.
        /// </summary>
        public static string MENU_TRABAJADOR_TODOS {
            get {
                return ResourceManager.GetString("MENU_TRABAJADOR_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        public static string MENU_UNIDAD_HERRAMIENTAS {
            get {
                return ResourceManager.GetString("MENU_UNIDAD_HERRAMIENTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maquinarias.
        /// </summary>
        public static string MENU_UNIDAD_MAQUINARIA {
            get {
                return ResourceManager.GetString("MENU_UNIDAD_MAQUINARIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string MENU_USUARIO {
            get {
                return ResourceManager.GetString("MENU_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Datos.
        /// </summary>
        public static string MENU_USUARIO_ACTUALIZA_DATOS {
            get {
                return ResourceManager.GetString("MENU_USUARIO_ACTUALIZA_DATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Perfil.
        /// </summary>
        public static string MENU_USUARIO_PERFIL {
            get {
                return ResourceManager.GetString("MENU_USUARIO_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Usuarios.
        /// </summary>
        public static string MENU_USUARIO_TODOS {
            get {
                return ResourceManager.GetString("MENU_USUARIO_TODOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string OBRA_Cliente {
            get {
                return ResourceManager.GetString("OBRA_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Cotización.
        /// </summary>
        public static string OBRA_CREAR_TITULO {
            get {
                return ResourceManager.GetString("OBRA_CREAR_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string OBRA_Direccion {
            get {
                return ResourceManager.GetString("OBRA_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string OBRA_Duracion {
            get {
                return ResourceManager.GetString("OBRA_Duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string OBRA_Empresa {
            get {
                return ResourceManager.GetString("OBRA_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string OBRA_Estado {
            get {
                return ResourceManager.GetString("OBRA_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string OBRA_Fecha_Inicio {
            get {
                return ResourceManager.GetString("OBRA_Fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la Obra.
        /// </summary>
        public static string OBRA_Nombre {
            get {
                return ResourceManager.GetString("OBRA_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano.
        /// </summary>
        public static string OBRA_Plano {
            get {
                return ResourceManager.GetString("OBRA_Plano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra.
        /// </summary>
        public static string OBRA_Titulo {
            get {
                return ResourceManager.GetString("OBRA_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de Pago.
        /// </summary>
        public static string PAGO_Pagar {
            get {
                return ResourceManager.GetString("PAGO_Pagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string PARTIDA_Nombre {
            get {
                return ResourceManager.GetString("PARTIDA_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string PARTIDA_Nro {
            get {
                return ResourceManager.GetString("PARTIDA_Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string PARTIDA_Precio {
            get {
                return ResourceManager.GetString("PARTIDA_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string PARTIDA_Tipo {
            get {
                return ResourceManager.GetString("PARTIDA_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partida.
        /// </summary>
        public static string PARTIDA_Titulo {
            get {
                return ResourceManager.GetString("PARTIDA_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Alquiler.
        /// </summary>
        public static string PEDIDO_Alquilar_Titulo {
            get {
                return ResourceManager.GetString("PEDIDO_Alquilar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Pedido.
        /// </summary>
        public static string PEDIDO_Asignar_Titulo {
            get {
                return ResourceManager.GetString("PEDIDO_Asignar_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad de días.
        /// </summary>
        public static string PEDIDO_Cantidad_Dias {
            get {
                return ResourceManager.GetString("PEDIDO_Cantidad_Dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string PEDIDO_Empresa {
            get {
                return ResourceManager.GetString("PEDIDO_Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string PEDIDO_Estado {
            get {
                return ResourceManager.GetString("PEDIDO_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Entrea.
        /// </summary>
        public static string PEDIDO_Fecha_Entrega {
            get {
                return ResourceManager.GetString("PEDIDO_Fecha_Entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        public static string PEDIDO_Fecha_Inicio {
            get {
                return ResourceManager.GetString("PEDIDO_Fecha_Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obra.
        /// </summary>
        public static string PEDIDO_Obra {
            get {
                return ResourceManager.GetString("PEDIDO_Obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string PEDIDO_Precio {
            get {
                return ResourceManager.GetString("PEDIDO_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido.
        /// </summary>
        public static string PEDIDO_Titulo {
            get {
                return ResourceManager.GetString("PEDIDO_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajador.
        /// </summary>
        public static string PEDIDO_Trabajador {
            get {
                return ResourceManager.GetString("PEDIDO_Trabajador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string PEDIDO_Ubicacion {
            get {
                return ResourceManager.GetString("PEDIDO_Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al realizar la operación.
        /// </summary>
        public static string RESULT_ERROR {
            get {
                return ResourceManager.GetString("RESULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string TAB_Filtro {
            get {
                return ResourceManager.GetString("TAB_Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string TIPOPARTIDA_Descripcion {
            get {
                return ResourceManager.GetString("TIPOPARTIDA_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string TIPOPARTIDA_Nombre {
            get {
                return ResourceManager.GetString("TIPOPARTIDA_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nro.
        /// </summary>
        public static string TIPOPARTIDA_Nro {
            get {
                return ResourceManager.GetString("TIPOPARTIDA_Nro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo partida.
        /// </summary>
        public static string TIPOPARTIDA_Titulo {
            get {
                return ResourceManager.GetString("TIPOPARTIDA_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string TITLE_Eliminar {
            get {
                return ResourceManager.GetString("TITLE_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string TRABAJADOR_Apellido {
            get {
                return ResourceManager.GetString("TRABAJADOR_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar trabajador.
        /// </summary>
        public static string TRABAJADOR_Asignar {
            get {
                return ResourceManager.GetString("TRABAJADOR_Asignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string TRABAJADOR_Celular {
            get {
                return ResourceManager.GetString("TRABAJADOR_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dni.
        /// </summary>
        public static string TRABAJADOR_Dni {
            get {
                return ResourceManager.GetString("TRABAJADOR_Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string TRABAJADOR_Estado {
            get {
                return ResourceManager.GetString("TRABAJADOR_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string TRABAJADOR_Nombre {
            get {
                return ResourceManager.GetString("TRABAJADOR_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string TRABAJADOR_Tipo {
            get {
                return ResourceManager.GetString("TRABAJADOR_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajador.
        /// </summary>
        public static string TRABAJADOR_Titulo {
            get {
                return ResourceManager.GetString("TRABAJADOR_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Herramientas.
        /// </summary>
        public static string UNIDAD_Asignar {
            get {
                return ResourceManager.GetString("UNIDAD_Asignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string UNIDAD_Cantidad {
            get {
                return ResourceManager.GetString("UNIDAD_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristica 1.
        /// </summary>
        public static string UNIDAD_Caracteristica1 {
            get {
                return ResourceManager.GetString("UNIDAD_Caracteristica1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristica 2.
        /// </summary>
        public static string UNIDAD_Caracteristica2 {
            get {
                return ResourceManager.GetString("UNIDAD_Caracteristica2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristica 3.
        /// </summary>
        public static string UNIDAD_Caracteristica3 {
            get {
                return ResourceManager.GetString("UNIDAD_Caracteristica3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálago.
        /// </summary>
        public static string UNIDAD_CATALAGO_Titulo {
            get {
                return ResourceManager.GetString("UNIDAD_CATALAGO_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string UNIDAD_Descripcion {
            get {
                return ResourceManager.GetString("UNIDAD_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string UNIDAD_Estado {
            get {
                return ResourceManager.GetString("UNIDAD_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        public static string UNIDAD_Imagen {
            get {
                return ResourceManager.GetString("UNIDAD_Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        public static string UNIDAD_Marca {
            get {
                return ResourceManager.GetString("UNIDAD_Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string UNIDAD_Modelo {
            get {
                return ResourceManager.GetString("UNIDAD_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string UNIDAD_Nombre {
            get {
                return ResourceManager.GetString("UNIDAD_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string UNIDAD_Precio {
            get {
                return ResourceManager.GetString("UNIDAD_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string UNIDAD_Serie {
            get {
                return ResourceManager.GetString("UNIDAD_Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Unidad.
        /// </summary>
        public static string UNIDAD_Tipo_Unidad {
            get {
                return ResourceManager.GetString("UNIDAD_Tipo_Unidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad.
        /// </summary>
        public static string UNIDAD_Titulo {
            get {
                return ResourceManager.GetString("UNIDAD_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string USUARIO_Apellido {
            get {
                return ResourceManager.GetString("USUARIO_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string USUARIO_Celular {
            get {
                return ResourceManager.GetString("USUARIO_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        public static string USUARIO_Direccion {
            get {
                return ResourceManager.GetString("USUARIO_Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dni.
        /// </summary>
        public static string USUARIO_Dni {
            get {
                return ResourceManager.GetString("USUARIO_Dni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string USUARIO_Email {
            get {
                return ResourceManager.GetString("USUARIO_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string USUARIO_Nombre {
            get {
                return ResourceManager.GetString("USUARIO_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string USUARIO_Rol {
            get {
                return ResourceManager.GetString("USUARIO_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string USUARIO_Titulo {
            get {
                return ResourceManager.GetString("USUARIO_Titulo", resourceCulture);
            }
        }
    }
}
