//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copreter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Copreter.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string BTN_Aceptar {
            get {
                return ResourceManager.GetString("BTN_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        public static string BTN_Filtrar {
            get {
                return ResourceManager.GetString("BTN_Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string BTN_Guardar {
            get {
                return ResourceManager.GetString("BTN_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        public static string CARD_TITLE {
            get {
                return ResourceManager.GetString("CARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string CLEINTE_Rol {
            get {
                return ResourceManager.GetString("CLEINTE_Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNI.
        /// </summary>
        public static string CLIENTE_DNI {
            get {
                return ResourceManager.GetString("CLIENTE_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string CLIENTE_Nombre {
            get {
                return ResourceManager.GetString("CLIENTE_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string CLIENTE_Titulo {
            get {
                return ResourceManager.GetString("CLIENTE_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta seguro de eliminar el registro.
        /// </summary>
        public static string MENSAJE_CONFIRMAR_ELIMINAR {
            get {
                return ResourceManager.GetString("MENSAJE_CONFIRMAR_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al realizar la operación.
        /// </summary>
        public static string RESULT_ERROR {
            get {
                return ResourceManager.GetString("RESULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string TAB_Filtro {
            get {
                return ResourceManager.GetString("TAB_Filtro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string TITLE_Eliminar {
            get {
                return ResourceManager.GetString("TITLE_Eliminar", resourceCulture);
            }
        }
    }
}
