CREATE TABLE [dbo].[T_Unidad] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [Serie]            NVARCHAR (100) NOT NULL,
    [Nombre]           NVARCHAR (100) NOT NULL,
    [Modelo]           NVARCHAR (100) NOT NULL,
    [Marca]            NVARCHAR (100) NOT NULL,
    [Precio]           DECIMAL (18)   NOT NULL,
    [Cantidad]         INT            NOT NULL,
    [CantidadDisponible]         INT            NOT NULL DEFAULT 0,
    [Descripcion]      NVARCHAR (500) NOT NULL,
    [Caracteristica1]  NVARCHAR (500) NOT NULL,
    [Caracteristica2]  NVARCHAR (500) NULL,
    [Caracteristica3]  NVARCHAR (500) NULL,
    [Id_Tipo_Unidad]   INT            NOT NULL,
    [Id_Estado_Unidad] INT            NOT NULL,
    [Imagen]           VARCHAR (MAX)  NULL,
        [BORRADO]                 BIT            DEFAULT ((0)) NOT NULL,
    [ID_USUARIO_REGISTRO]     INT            NOT NULL DEFAULT 1,
    [FECHA_REGISTRO]          DATETIME       NOT NULL DEFAULT GETDATE(),
    [FECHA_MODIFICACION]      DATETIME       NULL,
    [ID_USUARIO_MODIFICACION] INT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_T_Unidad_T_EstadoUnidad] FOREIGN KEY ([id_Estado_Unidad]) REFERENCES [dbo].[T_EstadoUnidad] ([ID]),
    CONSTRAINT [FK_T_Unidad_T_TipoUnidad] FOREIGN KEY ([id_Tipo_Unidad]) REFERENCES [dbo].[T_TipoUnidad] ([ID])
);

